plugins {
    id "dev.architectury.loom" version "1.3-SNAPSHOT"
    id "maven-publish"
    id "idea"
    id "java"
}

java {
    sourceCompatibility = targetCompatibility = JavaVersion.VERSION_17
}

version = "${mod_version}"
if (hasProperty("appendBuildNumber")) {
    version = version + "-" + appendBuildNumber.toString()
} else {
    version = version + "-0"
}

group = "${group_id}"
archivesBaseName = "${mod_id}-${minecraft_version}"

loom {
    // use this if you are using the official mojang mappings
    // and want loom to stop warning you about their license
    silentMojangMappingsLicense()

    // since loom 0.10, you are **required** to use the
    // "forge" block to configure forge-specific features,
    // such as the mixinConfigs array or datagen
    forge {
        // specify the mixin configs used in this mod
        // this will be added to the jar manifest as well!
        mixinConfigs = [
                "examplemod.mixins.json"
        ]

        // missing access transformers?
        // don't worry, you can still use them!
        // note that your AT *MUST* be located at
        // src/main/resources/META-INF/accesstransformer.cfg
        // to work as there is currently no config option to change this.
        // also, any names used in your access transformer will need to be
        // in SRG mapped ("func_" / "field_" with MCP class names) to work!
        // (both of these things may be subject to change in the future)
    }
}

processResources {
    inputs.property "version", project.version
    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }
}

//configurations {
//    runtime.exclude group: "ValkyrienWarfareRevamped", module: "valkyrienwarfare"
//}
//
//def omlib_local = false
//if (project.allprojects.findAll({ it.name == "OMLib" }).size() > 0) {
//    omlib_local = true
//}
//if (rootProject.name == "OMTControl") {
//    omlib_local = true
//}
//def ompd_local = false
//if (project.allprojects.findAll({ it.name == "OpenModularPassiveDefense" }).size() > 0) {
//    ompd_local = true
//}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    forge "net.minecraftforge:forge:${project.forge_version}"
//    deobfProvided "mezz.jei:jei_${minecraft_version}:${jei_version}:api"
//    testCompile "mezz.jei:jei_${minecraft_version}:${jei_version}:api"
//    deobfProvided "mcp.mobius.waila:Hwyla:${hwyla_version}_${minecraft_version_short}:api"
//    testCompile "mcp.mobius.waila:Hwyla:${hwyla_version}_${minecraft_version_short}:api"
//    deobfProvided "cofh:RedstoneFlux:${minecraft_version_short}-${redstoneflux_version}:universal"
//    testCompile "cofh:RedstoneFlux:${minecraft_version_short}-${redstoneflux_version}:universal"
//    deobfProvided "mcjty.theoneprobe:TheOneProbe-${minecraft_version_short}:${minecraft_version_short}-${top_version}"
//    testCompile "mcjty.theoneprobe:TheOneProbe-${minecraft_version_short}:${minecraft_version_short}-${top_version}"
//    deobfProvided "li.cil.oc:OpenComputers:MC${minecraft_version}-${oc_version}"
//    testCompile "li.cil.oc:OpenComputers:MC${minecraft_version}-${oc_version}"
//    deobfProvided "net.darkhax.tesla:Tesla-${minecraft_version_short}:${tesla_version}"
//    testCompile "net.darkhax.tesla:Tesla-${minecraft_version_short}:${tesla_version}"
//    if (!omlib_local) {
//        compileOnly "omtteam:omlib:${minecraft_version}-${omlib_version}:dev"
//        testCompile "omtteam:omlib:${minecraft_version}-${omlib_version}:dev"
//    } else {
//        compile project(":OMLib")
//        testCompile project(":OMLib")
//    }
//    if (ompd_local) {
//        runtime project(":OpenModularPassiveDefense")
//    }
//    testImplementation "org.junit.jupiter:junit-jupiter-api:5.2.0"
//    testImplementation("org.junit.jupiter:junit-jupiter-api:5.2.0")
//    testImplementation("org.junit.platform:junit-platform-launcher:1.1.0")
//    testRuntime("org.junit.jupiter:junit-jupiter-engine:5.2.0")
}

//junitPlatform {
//    platformVersion "1.0.3"
//    enableStandardTestTask true
//}

//task deobfJar(type: Jar) {
//    from sourceSets.main.output
//    classifier = "dev"
//}

//tasks.build.dependsOn deobfJar, sourceJar

publishing {
    tasks.publish.dependsOn "build"
    publications {
        mavenJava(MavenPublication) {
            groupId group_id
            version minecraft_version + "-" + project.version
            artifactId mod_id
            artifact jar
        }
    }
    repositories {
        mavenLocal()
    }
}

//// DETECTING COMMIT NAME AND ACTIVATING CURSE RELEASE \\\\

//def commit_release_type = getCommmitReleaseType()
//
//def getCommmitReleaseType() {
//    if (project.hasProperty("curseforge_key")) {
//        def stdout = new ByteArrayOutputStream()
//        try {
//            exec {
//                commandLine "git", "log", "-1", "--pretty=tformat:%s"
//                standardOutput = stdout
//            }
//        } catch (Exception e) {
//            System.print("SKIPPING CURSE RELEASE - FAILED TO RETRIEVE LAST COMMIT")
//            e.printStackTrace()
//            return "none"
//        }
//        String commit = stdout.toString().trim()
//
//        if (commit.startsWith("CRelease") || commit.startsWith("crelease")) {
//            System.out.println("FOUND NEW RELEASE - COMMIT: ".concat(commit)); return "release"
//        } else if (commit.startsWith("CBeta") || commit.startsWith("cbeta")) {
//            System.out.println("FOUND NEW BETA - COMMIT: ".concat(commit)); return "beta"
//        } else if (commit.startsWith("CAlpha") || commit.startsWith("calpha")) {
//            System.out.println("FOUND NEW ALPHA - COMMIT: ".concat(commit)); return "alpha"
//        } else {
//            System.out.println("SKIPPING CURSE RELEASE - COMMIT: " + commit); return "none"
//        }
//    }
//    System.out.println("SKIPPING CURSE RELEASE - NO CURSE API KEY")
//    return "none"
//}

//tasks.curseforge.enabled = project.hasProperty("curseforge_key") && commit_release_type != "none"
//curseforge {
//    if (project.hasProperty("curseforge_key") && commit_release_type != "none") {
//        System.out.println("ATTEMPTING CURSE RELEASE")
//        apiKey = project.properties["curseforge_key"]
//    } else {
//        return
//    }
//    project {
//        id = curse_project_id
//        addGameVersion "1.12.2"
//
//        relations {
//            requiredDependency "omlib"
//            optionalDependency "ompd"
//            optionalDependency "ender-io"
//            optionalDependency "redstone-flux"
//            optionalDependency "thermal-expansion"
//            optionalDependency "mekanism"
//            optionalDependency "opencomputers"
//            optionalDependency "computercraft"
//        }
//
//        mainArtifact(jar) {
//            releaseType = commit_release_type
//            changelog = file("${projectDir}/change_log.html").text
//            changelogType = "html"
//        }
//
//        addArtifact(sourceJar) {
//            releaseType = "alpha"
//            changelog = file("${projectDir}/change_log.html").text
//            changelogType = "html"
//        }
//
//        addArtifact(deobfJar) {
//            releaseType = "alpha"
//            changelog = file("${projectDir}/change_log.html").text
//            changelogType = "html"
//        }
//    }
//}
